// Central list of allowed icon identifiers for categories and a helper to resolve components.
// We import only the icons we allow to keep bundle size small.
import {
  Leaf,
  Sprout,
  FlaskRound,
  FlaskConical,
  Atom,
  GraduationCap,
  HeartPulse,
  Sun,
  Waves,
  Building2,
  ShieldAlert,
  Cpu,
  Coins,
  BookOpen,
  Globe2,
  Microscope,
  Beaker,
  TestTube,
  TestTube2,
  Brain,
  Telescope,
  Pipette,

  Zap,
  TreePine,
  Thermometer,
  Map,
  MapPin,
} from "lucide-react";

// Whitelist a small, tasteful set. Values must match exported Lucide icon component names.
export const CATEGORY_ICON_OPTIONS = [
  // General research
  { value: "Microscope", label: "Microscope" },
  { value: "FlaskConical", label: "Flask (Conical)" },
  { value: "Leaf", label: "Leaf" },
  { value: "Sprout", label: "Sprout" },
  { value: "FlaskRound", label: "Flask (Round)" },
  { value: "Atom", label: "Atom" },
  { value: "Beaker", label: "Beaker" },
  { value: "TestTube", label: "Test Tube" },
  { value: "TestTube2", label: "Test Tube 2" },
  { value: "Brain", label: "Brain" },
  { value: "Pipette", label: "Pipette" },
  { value: "Telescope", label: "Telescope" },
  { value: "GraduationCap", label: "Education" },
  { value: "HeartPulse", label: "Health" },
  { value: "Sun", label: "Climate" },
  { value: "Waves", label: "Environment" },
  { value: "Building2", label: "Community" },
  { value: "ShieldAlert", label: "Disaster Risk" },
  { value: "Cpu", label: "Technology" },
  { value: "Zap", label: "Energy" },
  { value: "Coins", label: "Funding" },
  { value: "BookOpen", label: "Research" },
  { value: "Globe2", label: "Global" },
  { value: "TreePine", label: "Forestry" },
  { value: "Thermometer", label: "Temperature" },
  { value: "Map", label: "Map" },
  { value: "MapPin", label: "Location" },
];

export function getLucideIconByName(name) {
  if (!name || typeof name !== "string") return null;
  const map = {
    Leaf,
    Sprout,
    FlaskRound,
    FlaskConical,
    Atom,
    GraduationCap,
    HeartPulse,
    Sun,
    Waves,
    Building2,
    ShieldAlert,
    Cpu,
    Coins,
    BookOpen,
    Globe2,
    Microscope,
    Beaker,
    TestTube,
    TestTube2,
    Brain,
    Telescope,
    Pipette,
    Zap,
    TreePine,
    Thermometer,
    Map,
    MapPin,
  };
  return map[name] || null;
}
